### ISSUE TITLE
[BUG] [Swift 6.2] Conflicting String.Output typealias between swift-standards and swift-svg-rendering

### ISSUE THREAD

**Issue by icedoutxcv** [coenttb/swift-html#6]
swift-html 0.17.2 fails to build on Swift 6.2 due to conflicting String extensions. The swift-standards package (>= 0.25.0)
   defines String: Parsing.Parser with Output = Void, which conflicts with swift-svg-rendering's String: SVG.View requiring
  Output = UInt8.

  To Reproduce

  1. Clone the repo: git clone https://github.com/coenttb/swift-html.git
  2. Checkout latest tag: git checkout 0.17.2
  3. Build: swift build

  Expected Behavior

  Project builds successfully.

  Actual Behavior

  Build fails with:
  String+SVG.swift:15:1: error: type 'String' does not conform to protocol 'SVG.View'
  'SVG.View' requires the types 'String.Output' and 'UInt8' be equivalent

  SPM resolves swift-standards to 0.30.1, which introduces the conflicting String: Parsing.Parser extension.

  Environment

  - Swift version: 6.2.1
  - OS version: macOS 26.0
  - Package version: 0.17.2

  Additional Context

  Workaround: Pin swift-standards to version < 0.25.0 (e.g., 0.21.0) which doesn't have the String: Parsing.Parser extension.

  Affected packages: swift-standards, swift-svg-rendering, swift-html

  Suggested fixes:
  ??
